
default_twitter: &default_twitter
# development:
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>

development:
  secret_key_base: 31458a41b975f056747a75753abfe6a7e1f5d5387090b6deed2f3f1d39aa866c1f251178188efaf0a23eee54a64f9eb184e05d20275f1bd6c7c869098a1eab58
  <<: *default_twitter

test:
  secret_key_base: 761045bf64aadeca47f3c999639cd3d8e2798a27251381becb967fb1ff5a7290f02a877e0b9c3d5d85f16813d576eaf680dc8550e8e9d507159b8518c533b990
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
